name: Build macOS Executável

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checar código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.1'

      - name: Instalar PyInstaller
        run: pip install pyinstaller

      - name: Gerar executável
        run: |
          pyinstaller \
            --onefile \
            --windowed \
            --name CASDbot \
            --icon paper-plane.ico
            main.py

      - name: Publicar artefato
        uses: actions/upload-artifact@v4
        with:
          name: casdbot-macos
          path: dist/CASDbot
