name: Build macOS Executable

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/Library/Caches/pip
          key: pip-${{ runner.os }}-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            pip-${{ runner.os }}-

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build .app (GUI)
        run: |
          pyinstaller \
            --windowed \
            --onefile \
            --name CASDbot \
            --icon paper-plane.ico \
            CASDbot.py
          # Resultado principal: dist/CASDbot.app

      - name: Fix permissions & pack .app (zip)
        run: |
          chmod +x "dist/CASDbot.app/Contents/MacOS/CASDbot"
          cd dist && zip -r casdbot-macos-app.zip "CASDbot.app"

      - name: Also pack CLI binary inside .app (tar.gz)
        run: |
          # Binário que vive dentro do app (útil para rodar via terminal)
          cd "dist/CASDbot.app/Contents/MacOS"
          tar -czf "../../../../casdbot-macos-bin.tar.gz" CASDbot

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: casdbot-macos
          path: |
            dist/casdbot-macos-app.zip
            casdbot-macos-bin.tar.gz
